name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with flake8 (if available)
      run: |
        pip install flake8 || true
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
        
    - name: Test API endpoints
      run: |
        # Start the application in background
        python api/app.py &
        APP_PID=$!
        
        # Wait for the application to start
        sleep 5
        
        # Test endpoints
        curl -f http://localhost:8000/ || exit 1
        curl -f http://localhost:8000/health || exit 1
        curl -f http://localhost:8000/api/v1/agent || exit 1
        
        # Stop the application
        kill $APP_PID

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile_Version2.txt -t ai-alpha:${{ github.sha }} .
        
    - name: Test Docker container
      run: |
        # Run container in background
        docker run -d -p 8000:8000 --name test-container ai-alpha:${{ github.sha }}
        
        # Wait for container to start
        sleep 10
        
        # Test endpoints
        curl -f http://localhost:8000/ || exit 1
        curl -f http://localhost:8000/health || exit 1
        curl -f http://localhost:8000/api/v1/agent || exit 1
        
        # Stop and remove container
        docker stop test-container
        docker rm test-container
        
    - name: Log in to Docker Hub (optional)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Push to Docker Hub (optional)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker tag ai-alpha:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/ai-alpha:latest
        docker tag ai-alpha:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/ai-alpha:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ai-alpha:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ai-alpha:${{ github.sha }}